language: swift
osx_image: xcode12
before_install:
  - "pod install"
  - "pod repo update"
  - "gem install cocoapods"
before_script: 
  - "./scripts/add-keys.sh"
after_script:
  - "./scripts/remove-key.sh"
script:
  - "./scripts/buildPrebidMobile.sh"
  - "./scripts/testPrebidMobile.sh"
  - "./scripts/testPrebidDemo.sh"
  # - "./scripts/swiftLint.sh"
